language: objective-c

osx_image: xcode7.3

xcode_workspace: Phoenix.xcworkspace
xcode_scheme: Phoenix

xcode_sdk: macosx10.11

notifications:
    email: false

before_install: gem install bundler
script: xctool -workspace $TRAVIS_XCODE_WORKSPACE -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK build

matrix:

    include:
        - osx_image: xcode7.2
        - osx_image: xcode7.1
        - osx_image: xcode7
