language: objective-c

xcode_workspace: Phoenix.xcworkspace
xcode_scheme: Phoenix

xcode_sdk: macosx10.15

notifications:
  email: false

before_install:
  - gem install xcpretty
  - npm install

matrix:
  include:
    - osx_image: xcode11.3
    - osx_image: xcode11.2
    - osx_image: xcode11.1
    - osx_image: xcode11
